### ISSUE TITLE
群晖docker一直处于重启状态

### ISSUE THREAD

**Issue by Barry2012** [amtoaer/bili-sync#13]
config.json配置正确，并且放到了配置文件夹下，权限也给了。但是一直处于重启状态，日志如下
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json

**Comment by Barry2012** [comment]
完整日志如下：
<html>
<body>
<div class="x-grid3-row x-grid3-row-selected" role="row" id="ext-gen11791" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-color: rgb(172, 172, 172) rgb(172, 172, 172) rgb(235, 240, 245); border-image: initial; cursor: default; width: 2248px; background-image: none; background-color: rgb(230, 245, 255) !important; color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
Traceback (most recent call last): | stdout
-- | --


</div>
</body>
</html>
