### ISSUE TITLE
群晖docker运行后一直处于重启状态

### ISSUE THREAD

**Issue by Barry2012** [amtoaer/bili-sync#14]
config.json配置正确，并确放到了config文件夹下了，权限也给了，但是不知道为何群晖docker运行后一直处于重启状态，部分日志如下，最后一句是载入配置文件失败，试了很多次，还是不行。
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
                                 ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 819: invalid continuation byte
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
                                 ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 819: invalid continuation byte
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json

**Comment by amtoaer** [comment]
这个报错是配置文件用 utf-8 编码没有正常解析。 
可以确认一下配置文件的内容是否使用了 utf-8 外的编码，或者包含一些无效字符。

**Comment by Barry2012** [comment]
已解决，应该就是编码格式问题

**Comment by jianzhichu** [comment]
我的运行起来，没日志。。。直接退出
