### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ariakeumi** [amtoaer/bili-sync#20]
启动后自动停止了。

日志：

2023-12-31 05:02:59.672 | INFO     | __main__:entry:41 - Running daemon...
2023-12-31 05:02:59.881 | INFO     | processor:process_favorite:104 - Start to process favorite 1097388686: 默认收藏夹
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 125, in process_favorite
    bvid__in=[media["bvid"] for media in favorite_video_list["medias"]],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-12-31 05:03:12.404 | INFO     | __main__:entry:41 - Running daemon...
2023-12-31 05:03:12.590 | INFO     | processor:process_favorite:104 - Start to process favorite 1097388686: 默认收藏夹
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 125, in process_favorite
    bvid__in=[media["bvid"] for media in favorite_video_list["medias"]],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2023-12-31 05:06:06.916 | INFO     | __main__:entry:41 - Running daemon...
2023-12-31 05:06:07.087 | INFO     | processor:process_favorite:104 - Start to process favorite 1097388686: 默认收藏夹
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 125, in process_favorite
    bvid__in=[media["bvid"] for media in favorite_video_list["medias"]],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
No upgrade items found
No upgrade items found
No upgrade items found

**Comment by amtoaer** [comment]
可参考文档尝试最新版本。
