### ISSUE TITLE
正常运行一段时间之后，就出现陷入重启状态，报错TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Barry2012** [amtoaer/bili-sync#21]
2023-12-31 16:14:43.049 | INFO     | processor:process_favorite:150 - Favorite 1410947741 Musics processed successfully.
2023-12-31 16:14:43.168 | INFO     | processor:process_favorite:104 - Start to process favorite 146022041: 默认收藏夹
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 125, in process_favorite
    bvid__in=[media["bvid"] for media in favorite_video_list["medias"]],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Barry2012** [comment]
No upgrade items found
2024-01-02 12:59:18.231 | INFO     | __main__:entry:41 - Running daemon...
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 100, in process_favorite
    favorite_video_list = await favorite_list.get_video_favorite_list_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/favorite_list.py", line 257, in get_video_favorite_list_content
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 82, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数
No upgrade items found
2024-01-02 12:59:20.503 | INFO     | __main__:entry:41 - Running daemon...
Traceback (most recent call last):
  File "/app/entry.py", line 50, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 43, in entry
    await process()
  File "/app/processor.py", line 95, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 100, in process_favorite
    favorite_video_list = await favorite_list.get_video_favorite_list_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/favorite_list.py", line 257, in get_video_favorite_list_content
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 82, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数

**Comment by et9930** [comment]
貌似是拉取合集有问题，只能拉取自己创建的收藏夹，不能拉收藏的合集

**Comment by amtoaer** [comment]
可参考文档尝试最新版本。
