### ISSUE TITLE
httpcore.ConnectTimeout

### ISSUE THREAD

**Issue by CATinTIN** [amtoaer/bili-sync#3]
只下载到了封面图和nfo文件，日志主要是http 超时，config不应该有问题呀，，，，
拜托了。。。

**Comment by amtoaer** [comment]
从 ConnectTimeout 这个错误和视频没下载成功的表现来看，可能是视频的下载地址没有解析出来，或者没有成功连接视频的下载地址，如果有详细的异常上下文可以进一步缩小范围，可以的话求发一下异常上下文信息。

**Comment by CATinTIN** [comment]
> 从 ConnectTimeout 这个错误和视频没下载成功的表现来看，可能是视频的下载地址没有解析出来，或者没有成功连接视频的下载地址，如果有详细的异常上下文可以进一步缩小范围，可以的话求发一下异常上下文信息。

感谢回复，目前更新了一下docker bili-sync, 然后这里是日志：

  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 29, in entry
    await process()
  File "/app/processor.py", line 100, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 105, in process_favorite
    favorite_video_list = await favorite_list.get_video_favorite_list_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/favorite_list.py", line 257, in get_video_favorite_list_content
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 82, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数
2023-12-05 20:20:29.641 | INFO     | __main__:entry:27 - Running daemon...
Traceback (most recent call last):
  File "/app/entry.py", line 36, in <module>
    runner.run(entry())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/app/entry.py", line 29, in entry
    await process()
  File "/app/processor.py", line 100, in process
    await process_favorite(favorite_id)
  File "/app/processor.py", line 105, in process_favorite
    favorite_video_list = await favorite_list.get_video_favorite_list_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/favorite_list.py", line 257, in get_video_favorite_list_content
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bilibili_api/utils/network.py", line 82, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数
Success upgrade 2_20231204003326_update.py

**Comment by CATinTIN** [comment]
> 从 ConnectTimeout 这个错误和视频没下载成功的表现来看，可能是视频的下载地址没有解析出来，或者没有成功连接视频的下载地址，如果有详细的异常上下文可以进一步缩小范围，可以的话求发一下异常上下文信息。


感谢回复，请看日志：

2023-12-05 20:26:55.545 | INFO     | processor:process_favorite:155 - Favorite 62420167 默认收藏夹 processed successfully.
No upgrade items found
2023-12-05 20:27:30.878 | INFO     | __main__:entry:27 - Running daemon...
2023-12-05 20:27:31.071 | INFO     | processor:process_favorite:109 - Start to process favorite 62420167: 默认收藏夹
2023-12-05 20:27:31.384 | INFO     | processor:process_video:166 - Start to process video BV1tQ4y187G7 【魔改】【11640工程】低强度的移动办公，一个旧手机就够了
2023-12-05 20:27:31.384 | INFO     | processor:process_video:166 - Start to process video BV1eN411L7eU 【睡前消息678】不怕雨果奖内定，就怕给三体丢脸
2023-12-05 20:27:31.385 | INFO     | processor:process_video:166 - Start to process video BV1eN41177Ko 【睡前消息677】红米十年纪念+近期消息回顾
2023-12-05 20:27:31.385 | INFO     | processor:process_video:166 - Start to process video BV1Wc411Q7FW 漫步101国道，马督工回承德【我们生长的地方｜第二季01】
2023-12-05 20:27:31.386 | INFO     | processor:process_video:189 - Upper 3493104613067249 跨界朋克 already exists, skipped.
2023-12-05 20:27:31.386 | INFO     | processor:process_video:189 - Upper 316568752 马督工 already exists, skipped.
2023-12-05 20:27:31.387 | INFO     | processor:process_video:189 - Upper 316568752 马督工 already exists, skipped.
2023-12-05 20:27:31.387 | INFO     | processor:process_video:189 - Upper 316568752 马督工 already exists, skipped.
2023-12-05 20:27:36.574 | ERROR    | processor:process_video:316 - Failed to process video BV1Wc411Q7FW 漫步101国道，马督工回承德【我们生长的地方｜第二季01】
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 190, in connect_tcp
    addr_obj = ip_address(remote_host)
               │          └ 'xy220x200x20x145xy.mcdn.bilivideo.cn'
               └ <function ip_address at 0x14e865749120>
  File "/usr/local/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')

ValueError: 'xy220x200x20x145xy.mcdn.bilivideo.cn' does not appear to be an IPv4 or IPv6 address


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
          └ <anyio._backends._asyncio.CancelScope object at 0x14e860e73110>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
            │     │   │                  │     └ <function connect_tcp at 0x14e8649e1bc0>
            │     │   │                  └ <module 'anyio' from '/usr/local/lib/python3.11/site-packages/anyio/__init__.py'>
            │     │   └ <class 'anyio.abc.ByteStream'>
            │     └ <module 'anyio.abc' from '/usr/local/lib/python3.11/site-packages/anyio/abc/__init__.py'>
            └ <module 'anyio' from '/usr/local/lib/python3.11/site-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 193, in connect_tcp
    gai_res = await getaddrinfo(
                    └ <function getaddrinfo at 0x14e8649e20c0>

asyncio.exceptions.CancelledError: Cancelled by cancel scope 14e860e73110


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
         │     │          └ 5.0
         │     └ <function fail_after at 0x14e8649725c0>
         └ <module 'anyio' from '/usr/local/lib/python3.11/site-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x14e860f139c0>
    │    │   │     │    └ CancelledError('Cancelled by cancel scope 14e860e73110')
    │    │   │     └ <class 'asyncio.exceptions.CancelledError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object fail_after at 0x14e861529540>
    └ <contextlib._GeneratorContextManager object at 0x14e860e72f90>
  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError

TimeoutError


The above exception was the direct cause of the following exception:
。。。。

**Comment by amtoaer** [comment]
感觉是你的 dns 有问题，没有把 ip 解出来：
![image](https://github.com/amtoaer/bili-sync/assets/32017007/964294e8-ba62-46ed-a48e-7fe9bd633d5c)
可以修改完 dns 重试看看。

**Comment by amtoaer** [comment]
有点怪，不太清楚了。视频地址的解析我是直接调用的上游 [bilibili api](https://github.com/Nemo2011/bilibili-api) 库，在我这里是能正常工作的。 😢

**Comment by zzsx644** [comment]
我排查了一下，是 dns 缓存造成的。关闭 dns缓存可以解决
