### ISSUE TITLE
群晖docker 启动后停止

### ISSUE THREAD

**Issue by qiaqiaxian** [amtoaer/bili-sync#52]
日志显示如下

> 2024/04/03 21:51:31	stdout	[32m2024-04-03 21:51:31.651[0m | [1mINFO    [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [1mDone, exited.[0m
2024/04/03 21:51:31	stdout	[32m2024-04-03 21:51:31.411[0m | [1mINFO    [0m | [36m__main__[0m:[36m<module>[0m:[36m53[0m - [1mCleaning up resources...[0m
2024/04/03 21:51:31	stdout	[31m[1mTypeError[0m:[1m 'NoneType' object is not iterable[0m
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	    [36m              └ [0m[36m[1m<FavoriteList: 2429843250>[0m
2024/04/03 21:51:31	stdout	    [36m              │                                              └ [0m[36m[1m{'info': {'id': 2429843250, 'fid': 24298432, 'mid': 348139750, 'attr': 23, 'title': '旅行', 'cover': 'http://i1.hdslb.com/bfs/a...[0m
2024/04/03 21:51:31	stdout	    [1mfavorite_list[0m[35m[1m=[0m[1mfav_list[0m[1m,[0m [1mbvid__in[0m[35m[1m=[0m[1m[[0m[1mmedia[0m[1m[[0m[36m"bvid"[0m[1m][0m [35m[1mfor[0m [1mmedia[0m [35m[1min[0m [1mfavorite_video_list[0m[1m[[0m[36m"medias"[0m[1m][0m[1m][0m
2024/04/03 21:51:31	stdout	  File "[32m/app/[0m[32m[1mprocessor.py[0m", line [33m125[0m, in [35mprocess_favorite[0m
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	    [36m      └ [0m[36m[1m<function process_favorite at 0x7f49c11d1080>[0m
2024/04/03 21:51:31	stdout	    [36m      │                └ [0m[36m[1m2429843250[0m
2024/04/03 21:51:31	stdout	    [35m[1mawait[0m [1mprocess_favorite[0m[1m([0m[1mfavorite_id[0m[1m)[0m
2024/04/03 21:51:31	stdout	  File "[32m/app/[0m[32m[1mprocessor.py[0m", line [33m100[0m, in [35mprocess[0m
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	    [36m      └ [0m[36m[1m<function process at 0x7f49c11d0fe0>[0m
2024/04/03 21:51:31	stdout	    [35m[1mawait[0m [1mprocess[0m[1m([0m[1m)[0m
2024/04/03 21:51:31	stdout	  File "[32m/app/[0m[32m[1mentry.py[0m", line [33m38[0m, in [35mentry[0m
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	    return future.result()
2024/04/03 21:51:31	stdout	  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024/04/03 21:51:31	stdout	           └ <asyncio.runners.Runner object at 0x7f49c510dc10>
2024/04/03 21:51:31	stdout	           │    └ <uvloop.Loop running=False closed=False debug=False>
2024/04/03 21:51:31	stdout	           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
2024/04/03 21:51:31	stdout	           │    │     │                  └ <Task finished name='Task-1' coro=<entry() done, defined at /app/entry.py:17> exception=TypeError("'NoneType' object is not i...
2024/04/03 21:51:31	stdout	    return self._loop.run_until_complete(task)
2024/04/03 21:51:31	stdout	  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	    [36m└ [0m[36m[1m<asyncio.runners.Runner object at 0x7f49c510dc10>[0m
2024/04/03 21:51:31	stdout	    [36m│      └ [0m[36m[1m<function Runner.run at 0x7f49c507ede0>[0m
2024/04/03 21:51:31	stdout	    [36m│      │   └ [0m[36m[1m<function entry at 0x7f49c4a98a40>[0m
2024/04/03 21:51:31	stdout	    [1mrunner[0m[35m[1m.[0m[1mrun[0m[1m([0m[1mentry[0m[1m([0m[1m)[0m[1m)[0m
2024/04/03 21:51:31	stdout	> File "[32m/app/[0m[32m[1mentry.py[0m", line [33m47[0m, in [35m<module>[0m
2024/04/03 21:51:31	stdout	
2024/04/03 21:51:31	stdout	[33m[1mTraceback (most recent call last):[0m
2024/04/03 21:51:31	stdout	[32m2024-04-03 21:51:31.069[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m49[0m - [31m[1mUnexpected error occurred, exiting...[0m
2024/04/03 21:51:31	stdout	[32m2024-04-03 21:51:31.056[0m | [1mINFO    [0m | [36mprocessor[0m:[36mprocess_favorite[0m:[36m111[0m - [1mStart to process favorite 2429843250: 旅行.[0m
2024/04/03 21:51:30	stdout	[32m2024-04-03 21:51:30.935[0m | [1mINFO    [0m | [36mprocessor[0m:[36mprocess_favorite[0m:[36m138[0m - [1mFavorite 2570330750 开发 has been processed.[0m
2024/04/03 21:51:30	stdout	[32m2024-04-03 21:51:30.668[0m | [1mINFO    [0m | [36mprocessor[0m:[36mprocess_favorite[0m:[36m111[0m - [1mStart to process favorite 2570330750: 开发.[0m
2024/04/03 21:51:30	stdout	[32m2024-04-03 21:51:30.562[0m | [1mINFO    [0m | [36mprocessor[0m:[36mprocess_favorite[0m:[36m138[0m - [1mFavorite 762473650 默认收藏夹 has been processed.[0m
2024/04/03 21:51:29	stdout	[32m2024-04-03 21:51:29.785[0m | [1mINFO    [0m | [36mprocessor[0m:[36mprocess_favorite[0m:[36m111[0m - [1mStart to process favorite 762473650: 默认收藏夹.[0m
2024/04/03 21:51:29	stdout	[32m2024-04-03 21:51:29.244[0m | [1mINFO    [0m | [36m__main__[0m:[36mentry[0m:[36m36[0m - [1mRunning daemon...[0m
2024/04/03 21:51:28	stdout	[33mNo upgrade items found[0m

**Comment by amtoaer** [comment]
这个一般是因为收藏夹里的内容是 None，麻烦确认下你的收藏夹 ID 没有填错，以及对应的收藏夹不是空的

**Comment by qiaqiaxian** [comment]
> 这个一般是因为收藏夹里的内容是 None，麻烦确认下你的收藏夹 ID 没有填错，以及对应的收藏夹不是空的

谢谢回复，检查过了还是一样
不过我好像看到Readme的配置示例好像是变了吗？一直没注意到

**Comment by amtoaer** [comment]
嗯嗯，因为最近用 rust 重写了项目，不过还没 release，docker 用的是之前 python 的版本。
这个收藏夹是可以公开访问的吗，如果是的话可以发一下 id，我来试试手动调下接口。
或者如果你知道如何编辑文件的话，在 https://github.com/amtoaer/bili-sync/blob/0b3434f5fd8d6901455aff6cc03edd004a062873/processor.py#L123 这个位置添加一行 `logger.error(favorite_video_list)` 查看一下日志打印。

**Comment by qiaqiaxian** [comment]
啊！你提醒了我！确实看了下是私密！但是之前一直也是私密呢，没变过。现在公开了没出错，这是什么问题

**Comment by amtoaer** [comment]
正常来说，只要私密收藏夹属于配置文件中那个凭据对应的b站账号就不应该会有问题才对，我这里也是这样用的，不理解为什么（

**Comment by qiaqiaxian** [comment]
我还确认了几遍，把这个出错的公开后，其他还是私密，
然后就正常了😂
