### ISSUE TITLE
大佬您好，目前有支持多收藏夹同步吗

### ISSUE THREAD

**Issue by whkwkxsyf1991** [amtoaer/bili-sync#8]
如果有的话，配置文件应该什么格式嘞，如果没有后期会支持吗，多谢大佬的项目，非常实用

**Comment by amtoaer** [comment]
有支持的，在配置文件的 path_mapper 里写入多个键值对就好。
key 是需要同步的收藏夹 id（在网页 b 站里打开收藏夹，url 里应该会显示），value 是这个收藏夹里的视频需要下载到的位置。

**Comment by whkwkxsyf1991** [comment]
> 有支持的，在配置文件的 path_mapper 里写入多个键值对就好。
> key 是需要同步的收藏夹 id（在网页 b 站里打开收藏夹，url 里应该会显示），value 是这个收藏夹里的视频需要下载到的位置。

😭我有试过这个参数里面再加一行但是报错了，能辛苦下给个多收藏夹样例不

**Comment by amtoaer** [comment]
啊这，看看报错信息？

**Comment by whkwkxsyf1991** [comment]
![_bili-sync_logs.txt](https://github.com/amtoaer/bili-sync/files/13784428/_bili-sync_logs.txt)
大概时间点在28号的凌晨00:30之后的那个报错

**Comment by whkwkxsyf1991** [comment]
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json
Traceback (most recent call last):
  File "/app/settings.py", line 46, in load
    return Config.schema().loads(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/marshmallow/schema.py", line 755, in loads
    data = self.opts.render_module.loads(json_data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 61 (char 549)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/entry.py", line 7, in <module>
    from commands import (
  File "/app/commands.py", line 9, in <module>
    from models import FavoriteItem
  File "/app/models.py", line 15, in <module>
    from settings import settings
  File "/app/settings.py", line 76, in <module>
    settings = init_settings()
               ^^^^^^^^^^^^^^^
  File "/app/settings.py", line 67, in init_settings
    Config.load(DEFAULT_CONFIG_PATH)
  File "/app/settings.py", line 48, in load
    raise RuntimeError(f"Failed to load config file: {path}") from e
RuntimeError: Failed to load config file: /app/config/config.json

**Comment by whkwkxsyf1991** [comment]
![image](https://github.com/amtoaer/bili-sync/assets/131899817/3ae2edd6-1752-4b1e-b11f-f79fa7294fdb)
多谢大佬，已经搞定啦，我之前是换了一行，应该直接在后面加，我傻了，python字典格式我给整忘了，好久没用了，哈哈，其他小伙伴可以参考截图内容
